[package]
name = "five_easy_pieces"
description = "Five easy pieces on Rust concurrency"
repository = "https://github.com/servo/rust-mozjs"
version = "0.0.0"
authors = ["Gregory Terzian"]
license = "MPL-2.0"

[dependencies]
crossbeam-channel = "0.4"
rayon = "1"